[project]
name = "python-nix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "feast[aws]>=0.52.0",
    "numpy>=2.2.6",
    "pandas>=2.3.2",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]
